# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"video_info": "00_core.ipynb",
         "force_read": "00_core.ipynb",
         "eager_video_iterator": "00_core.ipynb",
         "brightest_frame": "00_core.ipynb",
         "Calibrator": "00_core.ipynb",
         "BrowserCalibrator": "00_core.ipynb",
         "VIDEOS": "00_core.ipynb",
         "DataSource": "00_core.ipynb",
         "videos_source": "00_core.ipynb",
         "xy_fft": "00_core.ipynb",
         "array_to_wx": "02_slideshow.ipynb",
         "Panel": "02_slideshow.ipynb",
         "Frame": "02_slideshow.ipynb",
         "slideshow": "02_slideshow.ipynb"}

modules = ["core.py",
           "dataset.py",
           "slideshow.py"]

doc_url = "https://ababino.github.io/seeing_through_water/"

git_url = "https://github.com/ababino/seeing_through_water/tree/master/"

def custom_doc_links(name): return None
